# Generated by Django 5.0.4 on 2024-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_starts',
            field=models.IntegerField(choices=[(1, 'wrost'), (2, 'Not bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
